name: 20 - Workflow Security

on:
  pull_request:

jobs:
  unsafe-pr:
    runs-on: ubuntu-latest
    name: Unsafe PR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR title (unsafe)
        run: |
          title=${{ github.event.pull_request.title }}
          if [[ $title =~ ^feat ]]; then
            echo "PR is a feature"
            exit 0
          else
            echo "PR is not a feature"
            exit 1
          fi

  safer-pr:
    runs-on: ubuntu-latest
    name: Safer PR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR title (safe)
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ "$TITLE" =~ ^feat ]]; then
            echo "PR is a feature"
            exit 0
          else
            echo "PR is not a feature"
            exit 1
          fi
