name: 02 - Workflow Events

on:
  push:
  pull_request:
  schedule:
    - cron: '*/1 * * * *'   # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "This workflow was triggered by the event ${{ github.event_name }}"
