name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            node: 16.x

          - os: ubuntu-latest
            node: 18.x
          - os: ubuntu-latest
            node: 20.x
          - os: ubuntu-latest
            node: 21.x
            tag: experimental

          - os: windows-latest
            node: 18.x
          - os: windows-latest
            node: 20.x
          - os: windows-latest
            node: 21.x

    name: ${{ matrix.os }}-${{ matrix.node }}

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Fail if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: |
          echo "This is an experimental configuration. Failing intentionally."
          exit 1

      - name: Perform some tests
        run: |
          echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"
          sleep 10

      - name: Upload test results
        run: echo "Uploading test results"
