name: 19 - 1 - Managing Concurrency

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate Docker Ping URL
        run: |
          echo "Simulating unreachable URL ping..."
          for i in {1..20}; do
            echo "Trial $i: Trying to reach http://unreachable.url"
            curl --connect-timeout 2 http://unreachable.url || echo "Unreachable"
            sleep 5
          done

