name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18.x, 20.x, 21.x]
    name: ${{ matrix.os }}-${{ matrix.node }}

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Perform some tests
        run: echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"
